### ISSUE TITLE
I can't install NDK

### ISSUE THREAD

**Issue by Quiec** [vlang/vab#5]
Log:
```sh
➜  vab git:(master) ✗ ./vab install ndk
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

OS: macOS Mojave 10.14.6
V: `0.2 e4f94b6`

**Comment by Larpon** [comment]
@Quiec can you please post the output of `./vab doctor`?

**Comment by Quiec** [comment]
@Larpon I installed with Android Studio, no problem now. But I did not understand exactly how to create applications. Is there an example?

**Comment by Larpon** [comment]
Output from `./vab doctor` will still be helpful.

> But I did not understand exactly how to create applications. Is there an example?

Can you please open a separate issue with this?

**Comment by Larpon** [comment]
From what I can find on the net this error occurs when using Java > 8 and `cmdline-tools;1.0` 
A workaround for now would be to try and upgrade to `cmdline-tools;2.1`/`3.0` which should be compatible with newer Java versions
